# Generated by Django 5.1.1 on 2024-10-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='summa', max_length=30)),
                ('age', models.IntegerField(max_length=10)),
            ],
        ),
    ]
